version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8800:8800"
    networks:
      - my-network
    environment:
      - DB_HOST=host.docker.internal
      - DB_USER=root
      - DB_PASSWORD=pass
      - DB_DATABASE=crud
      - BACK_PORT=8800

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - my-network
    environment:
      - REACT_APP_API_URL=http://localhost:8800
    depends_on:
      - backend

networks:
  my-network:
    driver: bridge
